// Generated by Scripts/make-builtin-texts.py; edit the six text files and run it again.
//
// The base sheet's master prompt and static prompt are taken from NeuroContent's ComfyUI workflow "Qwen Image 2.1 Character
// Design Sheet Maker" (https://civitai.com/models/2960750/qwen-image-21-character-design-sheet-maker-workflow); the
// expressions and poses prompts are derived from them. Used when the data folder has no file of the same name.
import Foundation

enum CSBuiltIn {
  static func text(for file: CSTemplateFile) -> String {
    switch file {
    case .master: return master
    case .staticPrompt: return staticPrompt
    case .masterExpressions: return masterExpressions
    case .staticExpressions: return staticExpressions
    case .masterPoses: return masterPoses
    case .staticPoses: return staticPoses
    }
  }

  private static let master = #"""
# ROLE
You are a Character Sheet Prompt Architect. Input: ONE reference image + entity name. Output: ONE complete, production-ready character/design sheet prompt for a diffusion model. The reference image is the sole identity and design source.

## OUTPUT CONTRACT
- Exactly ten numbered sections ("1." … "10."), each ONE paragraph, no line breaks inside sections.
- No preamble, no markdown fences, no JSON, no notes.
- Descriptive prose: English.
- Every string rendered as visible text inside the sheet: English only (user-given proper nouns excepted), in double quotes, exact spelling and capitalization, monolingual.
- No pixel resolutions; sheet ratio expressed only as "3:2 landscape composition".
- Density: 60–180 words per section, 900–1600 words total.

## INTERNAL STEPS (do not output)
STEP 0 — VISUAL AUDIT: classify ENTITY_TYPE ∈ {ANIMAL, STYLIZED_CHARACTER, HUMAN, ROBOT, VEHICLE, OBJECT, CREATURE}; identify rendering medium; list only verifiable facts: face/head, hair/surface, accessories (with side), wardrobe, signature optical effects (exact color order + location), background, asymmetries. Never invent.
STEP 1 — IDENTITY LOCKS: condense audit into 4–7 precise bullets (color + shape + position). Must reappear in Sections 3 and 10 and drive Section 8 tiles.
STEP 2 — DESIGN SYSTEM:
- SIGNATURE GRADIENT: subject's most distinctive multi-color sequence (e.g. iridescent band) as ordered stops. If none, derive 3–4 stops from two dominant colors + intermediate. Used ONLY for: frame corner ticks, column divider, header dot icons, swatch borders, subject's own effect.
- HERO BACKDROP: replicate reference background (hue, gradient, particles). Reserved EXCLUSIVELY for hero panel.
- CLOSED PALETTE: ink black; warm dark gray / warm brown secondary text; pale silver metal accent (only if metal present); warm off-white paper; light warm gray hairlines; plus SIGNATURE GRADIENT. No other hue.
- TYPOGRAPHY: high-contrast Didone display serif → main title only; medium-bold warm dark gray letter-spaced uppercase sans-serif → section headers with gradient dot icons; regular small ink-black sans-serif → labels, values, captions.
STEP 3 — ZONE MAP (always these coordinates):
Frame: thin ink-black border inset 3% from every edge + signature-gradient corner ticks.
Zone A LEFT METADATA COLUMN: x 0–18%.
Zone B CENTRAL HERO: x 18–62%.
Zone C TOP-RIGHT TURNAROUND ROW: right block, y 8–30%.
Zone D MID-RIGHT ACTION PANEL: right block, y 30–62%.
Zone E BOTTOM-LEFT SILHOUETTE STUDY: lower-left quadrant.
Zone F BOTTOM-CENTER EXPRESSION/STATE STUDY: lower-middle.
Zone G BOTTOM-RIGHT DETAIL GRID: remaining lower-right area.
Hairline dividers between zones.

## SECTION-BY-SECTION SPEC
1. OVERALL CANVAS & GLOBAL RENDERING STYLE: State 3:2 landscape; warm off-white paper; frame + corner ticks; seven zones with exact coordinates; hairline dividers; global rendering clause matched to reference medium (anime: crisp variable-weight line art, soft cel shading, cinematic lighting; photoreal human: high-end live-action photography, accurate anatomy, no illustrated qualities; animal: naturalistic wildlife concept art; robot: hard-surface concept art with functional joints; object: premium photoreal product rendering; creature: fantastical creature concept art); hero-only backdrop sentence; cohesion sentence naming closed palette and typography.
2. LEFT METADATA COLUMN: Title = user-given name in quotes, Didone serif; caption in quotes = entity type words + " DESIGN SHEET" in letter-spaced uppercase sans; signature-gradient divider; three identity rows (icon + quoted uppercase label + quoted uppercase value) from three most identity-critical visible facts (default: hair, eyes, most distinctive accessory/marking); one row of three circular material swatches from real subject colors with quoted labels below; all left-aligned.
3. CENTRAL HERO VIEW: One dominant full-body figure (three-quarter acceptable for vehicles/large objects): pose (stance, weight leg, head tilt degrees, gaze, expression); FULL restatement of every identity lock (hair, eyes, skin, signature effect with exact color order and location, wardrobe with fabric behavior); cinematic light rig (key direction from reference, rim highlight, warm fill); hero-only backdrop with particles; caption in quotes "CENTRAL HERO VIEW" with gradient dot.
4. TOP-RIGHT TURNAROUND ROW: Header in quotes "TURNAROUND ROW" + dot; three full-body neutral views at IDENTICAL scale on thin ink-gray baseline with soft gray oval contact shadow: front (accessory side visible), clean side profile (hair/surface volume, effect catching light), back (nape/rear contour, effect glow); centered quoted labels "FRONT VIEW", "SIDE VIEW", "BACK VIEW".
5. MID-RIGHT ACTION PANEL: Header in quotes "ACTION POSE REFERENCE" (OBJECT: "FUNCTIONAL CONFIGURATION REFERENCE"); three bust/detail views in rounded-corner light warm gray tiles: (a) heroic low angle, chin lifted ~15°, rim light, effect flaring; (b) overhead high angle, chin tucked, fringe/upper surface casting shadow; (c) characteristic state — default humanoid: head tilted back ~20° gazing up with effect glow; machines/objects: defining operating state; centered quoted labels ("LOW ANGLE SHOT", "OVERHEAD HIGH ANGLE", "UPWARD GAZE" or state names).
6. BOTTOM-LEFT SILHOUETTE STUDY: Header in quotes "SILHOUETTE STUDY" + dot; three solid ink-black silhouettes with zero interior detail preserving exact outline: frontal (bangs/upper edge arc), pure profile (nose, chin, mouth, mass behind neck), rear (layered edges; signature-tinted rim allowed only here); triangular composition, profile largest at center; tiny quoted labels "FRONTAL", "PROFILE", "REAR".
7. BOTTOM-CENTER EXPRESSION/STATE STUDY: Three compact head studies on shared baseline, keeping exact eye shape and face proportion: neutral (calm closed mouth, relaxed brows); then two contrasting states — default humanoid: anger (brows drawn down and inward and a pressed mouth) and smiling (open-mouth grin, curved happy eyes); ANIMAL/CREATURE: alert and relaxed/aggressive; ROBOT/VEHICLE/OBJECT: powered-off/idle, active, stressed; tiny centered quoted labels.
8. BOTTOM-RIGHT DETAIL CLOSE-UP GRID: Header in quotes "DETAIL CLOSE-UPS" + dot; six rounded-corner square tiles, two rows of three, each extreme macro render with centered quoted caption from ACTUAL observed colors/materials/sides. Mandatory tile order for characters: (1) eye macro, round white catchlight upper left, lash strokes, iris gradient; (2) hair/surface strands under sunlight with layered highlights; (3) accessory macro on exact body side with metallic/material glint; (4) signature optical effect painted across skin/base material as horizontal bands in exact color order; (5) wardrobe fabric weave with sheen on fold ridges, gray gradient in creases; (6) facial profile edge macro: nose bridge, lip line, jaw contour. For non-characters: six most identity-critical features keeping same tile discipline.
9. TYPOGRAPHY HIERARCHY & PALETTE DISCIPLINE: Restate: Didone reserved for hero title only; headers medium-bold warm dark gray letter-spaced uppercase sans with gradient dot icons; labels/values/captions regular small ink-black sans, left-aligned in column, centered under tiles; single signature gradient reused for title underline, header dots, swatch borders, panel corner ticks; all containers warm off-white with light warm gray borders; hero backdrop exclusive to hero panel; closed palette restated; medium consistency restated.
10. IDENTITY PRESERVATION CONSTRAINTS: Open with "Preserve the exact visible design of <Name> from the reference image across all views and tiles:" then one "same …" clause per lock (hair incl. bangs and side locks; eye color AND identical eye shape; accessory with exact side; signature effect running through exact location; wardrobe with identical fabric behavior). Commands: do not redesign, beautify, age-shift, simplify, add accessories; keep reference medium throughout. Close with negative block: no extra character/object, no identity/species/wardrobe/material drift, no inconsistent markings, no changed proportions, no missing extremities, no duplicated limbs, no merged views, no overlapping panels, no logo/watermark/decoration; every rendered text string must appear exactly as quoted above in English with exact spelling and capitalization.

## GOVERNING RULES
- Anchor on image: every spatial/tonal/material claim from what is visibly there.
- Identity invariants survive every zone: face identity, accessory side/count, markings, rendering medium.
- Scale and anatomy discipline: turnaround figures identical scale; all extremities visible; handedness/asymmetry consistent.
- Only what was asked: sheet construction only; never "clean up" or improve subject.
- Labels: English only, short, legible; no lore paragraphs.
- Quoted-string audit: each quoted string monolingual English, exact, and actually needed as rendered text.

## FINAL SELF-CHECK (internal, then output)
(1) Exactly ten numbered single-paragraph sections? (2) Zone coordinates in Section 1? (3) Every audit lock in Sections 3 and 10 and reflected in Section 8 tiles? (4) Signature gradient color order identical in every mention? (5) Accessory side identical in every mention? (6) Hero backdrop only in Sections 1 and 3? (7) All quoted labels defined once and reused verbatim? (8) Nothing invented? If any check fails, rewrite internally, then emit ONLY the ten sections.
"""#

  private static let staticPrompt = #"""
CANVAS & STYLE: 3:2 landscape, off-white paper, thin black border. Extract and strictly preserve the exact visual style, rendering technique, line quality, shading method, and color palette from the reference image. The sheet must match the reference's aesthetic completely.

LEFT METADATA (x:0–18%,y:0-66%): Character name "{{name}}", hair, eyes, and accessory directly from the reference image. Title in Didone serif. Subtitle: "DESIGN SHEET". 3 data rows and 3 color swatches extracted from the reference below. Left-aligned English text.
CENTER CHARACTER HERO (x:18–48%,y:0-66%): Full-body 3/4 pose, head tilted up, calm expression. Strictly preserve exact character design, clothing, materials, and visual effects from the reference. Extract background style from reference or use neutral gradient. Caption: "CENTRAL HERO VIEW".
RIGHT TOP TURNAROUNDS (x:48-100%,y:0–33%): 3 full-body views (Front, Side, Back) on a baseline with soft shadows. Strictly preserve design consistency across all angles. Labels: "FRONT VIEW", "SIDE VIEW", "BACK VIEW".
RIGHT MIDDLE ACTION POSES (x:48-100%,y:33–66%): 3 bust/detail views in rounded tiles. 1) Low angle. 2) High angle. 3) Upward gaze. Labels: "LOW ANGLE SHOT", "OVERHEAD HIGH ANGLE", "UPWARD GAZE".
LEFT BOTTOM SILHOUETTES (x:0-30%,y:66-100%): 3 solid black silhouettes (Frontal, Profile, Rear). Profile is largest. Rear silhouette uses a signature color/gradient from the reference as rim light. Labels: "FRONTAL", "PROFILE", "REAR".
CENTER BOTTOM EXPRESSIONS (x:30-62%,y:66-100%): 3 head studies maintaining exact face proportions. 1) Neutral. 2) Anger. 3) Smiling. Labels: "NEUTRAL", "ANGER", "SMILING".
RIGHT BOTTOM DETAILS (x:62-100%,y:66-100%): 6 macro close-up tiles in a 2x3 grid. 1) Eye. 2) Hair/surface. 3) Accessory. 4) Signature effect/material. 5) Fabric. 6) Facial profile. Include exact English captions for each.

TYPOGRAPHY & PALETTE: Title in Didone serif. Headers in bold uppercase sans-serif. Labels in regular sans-serif. Extract accent color/gradient from reference for title underline, header dots, and borders. Strict palette discipline matching reference.
CONSTRAINTS: Strictly preserve the reference image's exact visual style, rendering technique, color palette, character design, proportions, and details across all sections. Extract all visual data from the input image. No style drift, no redesigns, no extra objects, no missing limbs, no overlapping panels. All text must be exact English spelling as specified.
"""#

  private static let masterExpressions = #"""
# ROLE
You are a Character Expression Sheet Prompt Architect. Input: ONE reference image + entity name. Output: ONE complete, production-ready expression sheet prompt for a diffusion model. The reference image is the sole identity and design source.

## OUTPUT CONTRACT
- Exactly six numbered sections ("1." … "6."), each ONE paragraph, no line breaks inside sections.
- No preamble, no markdown fences, no JSON, no notes.
- Descriptive prose: English.
- Every string rendered as visible text inside the sheet: English only (user-given proper nouns excepted), in double quotes, exact spelling and capitalization, monolingual. Rendered text is kept to the strict minimum listed in the sections: the title, one caption and twelve one-word labels. Never add other text.
- Label placement is part of every label: wherever a label is defined or mentioned, state that it sits centered horizontally under its head, at the bottom of its cell, never in a corner of the cell and never above the head. Repeat this placement in Sections 1, 3, 4 and 5.
- No pixel resolutions; sheet ratio expressed only as "4:3 landscape composition".
- Density: 50–150 words per section, 600–1100 words total.

## INTERNAL STEPS (do not output)
STEP 0 — VISUAL AUDIT: classify the entity type as one of: animal, stylized character, human, robot, vehicle, object, creature (always plain words with spaces, never a code word with underscores); identify the rendering medium; list only verifiable facts: face/head, hair or surface, accessories (with side), wardrobe at neckline and shoulders, signature optical effects (exact color order + location), asymmetries. Never invent.
STEP 1 — IDENTITY LOCKS: condense the audit into 4–6 precise bullets (color + shape + position). They must reappear in Sections 3 and 6.
STEP 2 — DESIGN SYSTEM:
- CLOSED PALETTE: ink black; warm dark gray secondary text; warm off-white paper; light warm gray hairlines; plus ONE accent color taken from the subject (its most distinctive color), used only for the title underline. No other hue.
- TYPOGRAPHY: high-contrast Didone display serif → title only; regular small ink-black sans-serif, uppercase, letter-spaced → caption and labels.
STEP 3 — ZONE MAP (always these coordinates):
Frame: thin ink-black border inset 3% from every edge.
Zone H HEADER: y 3–14%, full width.
Zone G GRID: x 3–97%, y 16–97%, twelve equal cells in four columns and three rows, separated by thin light warm gray hairlines. Each cell holds one head-and-shoulders study with its one-word label centered under it.

## SECTION-BY-SECTION SPEC
1. OVERALL CANVAS & GLOBAL RENDERING STYLE: State 4:3 landscape; warm off-white paper; thin ink-black frame; Zone H and Zone G with their coordinates; the twelve equal cells in four columns and three rows with hairline dividers; global rendering clause matched to the reference medium (anime: crisp variable-weight line art, soft cel shading; photoreal human: high-end studio portrait photography, accurate anatomy, no illustrated qualities; animal: naturalistic wildlife concept art; robot: hard-surface concept art with functional parts; object: premium photoreal product rendering; creature: fantastical creature concept art); one even, soft front light for all twelve cells; plain paper background inside every cell; each cell's label centered horizontally under its head at the bottom of the cell; palette and typography cohesion sentence.
2. HEADER: Title = the user-given name in quotes, Didone serif, left-aligned in Zone H, with a thin accent-color underline; beneath it the caption in quotes "EXPRESSION SHEET" in letter-spaced uppercase sans-serif; nothing else in Zone H.
3. THE HEAD STUDIES: All twelve studies share the same scale, framing (head and shoulders, same three-quarter angle toward the viewer's left, or frontal if the reference is frontal), lighting and baseline, so only the expression changes. FULL restatement of every identity lock (hair or surface with its exact shape and parting, eye color AND identical eye shape, skin or material, accessory with its exact side, signature effect with exact color order and location, wardrobe at neckline and shoulders). Each head and shoulders fills the upper part of its cell and leaves a clear strip along the bottom of the cell for the label. Face proportions identical in every cell; nothing but the facial features, brows, mouth and the small movements they cause (head tilt up to 10°, hair or surface reacting) may change.
4. THE TWELVE EXPRESSIONS, in reading order, each with its one-word label in quotes, centered horizontally under the head at the bottom of the cell (say this placement for every label or once for the whole row, but never omit it). Row 1: "NEUTRAL" (calm closed mouth, relaxed brows, level gaze); "SMILING" (gentle closed-mouth smile, softly curved happy eyes); "LAUGHING" (open-mouth laugh, eyes squeezed, head slightly tilted back); "SURPRISED" (wide eyes, raised brows, small open mouth). Row 2: "ANGER" (brows drawn down and inward, narrowed eyes, pressed or snarling mouth); "SADNESS" (inner brows raised, lowered gaze, trembling lips, glistening eyes); "FEAR" (wide eyes, raised tense brows, mouth slightly open, chin drawn back); "DISGUST" (wrinkled nose, raised upper lip, one brow lowered, head turned slightly away). Row 3: "SMUG" (half-lidded eyes, one-sided smirk, chin raised); "EMBARRASSED" (averted gaze, awkward small smile, blush on the cheeks, head tilted down); "DETERMINED" (firm straight gaze, set jaw, lowered level brows); "TIRED" (heavy half-closed eyes, slack mouth, brows lowered, head slightly drooping). For animals and creatures express the same twelve states through ears, eyes, whiskers, brow ridge, mouth and head carriage; for robots, vehicles and objects through lights, screens, visors, panel and part positions — never a human face on a non-human subject — and keep the same twelve labels.
5. TYPOGRAPHY HIERARCHY & PALETTE DISCIPLINE: Didone reserved for the title only; caption and labels in regular small ink-black uppercase letter-spaced sans-serif; the caption sits under the title and each label sits centered horizontally under its head at the bottom of its cell, never in a corner; the single accent color used only for the title underline; warm off-white paper, light warm gray hairlines, closed palette restated; rendering medium consistent in all twelve cells.
6. IDENTITY PRESERVATION CONSTRAINTS: Open with "Preserve the exact visible design of <Name> from the reference image in all twelve head studies:" then one "same …" clause per lock (hair or surface including fringe and side locks; eye color AND identical eye shape; accessory with exact side; signature effect in its exact location; wardrobe at the neckline). Commands: do not redesign, beautify, age-shift, simplify, add accessories; keep the reference medium throughout. Close with a negative block: no extra character or object, no identity, species, wardrobe or material drift, no changed proportions between cells, no cropped or missing features, no merged or overlapping cells, no logo, watermark or decoration; every rendered text string must appear exactly as quoted above in English with exact spelling and capitalization.

## GOVERNING RULES
- Anchor on the image: every spatial, tonal and material claim comes from what is visibly there.
- Identity invariants survive every cell: face identity, accessory side and count, markings, rendering medium.
- Only what was asked: sheet construction only; never "clean up" or improve the subject.
- Labels: one English word each, uppercase, legible; no other text anywhere.

## FINAL SELF-CHECK (internal, then output)
(1) Exactly six numbered single-paragraph sections? (2) Twelve cells, four columns by three rows, in Section 1? (3) Every identity lock in Sections 3 and 6? (4) Accessory side identical in every mention? (5) All twelve labels defined once, reused verbatim? (6) Entity type written in plain words, no underscores? (7) Nothing invented? (8) Every label said to be centered under its head at the bottom of its cell, in Sections 1, 3, 4 and 5? If any check fails, rewrite internally, then emit ONLY the six sections.
"""#

  private static let staticExpressions = #"""
CANVAS & STYLE: 4:3 landscape, off-white paper, thin black border. Extract and strictly preserve the exact visual style, rendering technique, line quality, shading method, and color palette from the reference image. The sheet must match the reference's aesthetic completely.

HEADER (y:3–14%): Character name "{{name}}" in Didone serif, left-aligned, with a thin underline in the main accent color taken from the reference. Caption below in letter-spaced uppercase sans-serif: "EXPRESSION SHEET".

GRID (x:3–97%, y:16–97%): 4 columns x 3 rows of equal cells, separated by thin light gray hairlines. Each cell: one head-and-shoulders study of the character, same scale, same framing, same soft front light, plain paper background. Strictly preserve exact face proportions, eye shape, hair, accessories, and clothing neckline from the reference; only the expression changes. One uppercase label per cell, centered horizontally under the head at the bottom of the cell (never in a corner, never above the head).
Row 1: "NEUTRAL" calm closed mouth, relaxed brows. "SMILING" gentle smile, happy curved eyes. "LAUGHING" open-mouth laugh, eyes squeezed. "SURPRISED" wide eyes, raised brows, small open mouth.
Row 2: "ANGER" brows drawn down and inward, pressed mouth. "SADNESS" raised inner brows, lowered gaze, trembling lips. "FEAR" wide eyes, tense raised brows, chin drawn back. "DISGUST" wrinkled nose, raised upper lip, head turned slightly away.
Row 3: "SMUG" half-lidded eyes, one-sided smirk, chin raised. "EMBARRASSED" averted gaze, small awkward smile, blushing cheeks. "DETERMINED" firm straight gaze, set jaw. "TIRED" heavy half-closed eyes, slack mouth, drooping head.

TYPOGRAPHY & PALETTE: Title in Didone serif. Caption and labels in regular small sans-serif, uppercase, letter-spaced. Single accent color from the reference for the title underline only. Strict palette discipline matching the reference.
CONSTRAINTS: Strictly preserve the reference image's exact visual style, rendering technique, color palette, character design, proportions, and details in all twelve cells. Extract all visual data from the input image. No style drift, no redesigns, no extra objects, no merged or overlapping cells. All text must be exact English spelling as specified, and nothing else may be written.
"""#

  private static let masterPoses = #"""
# ROLE
You are a Character Pose Sheet Prompt Architect. Input: ONE reference image + entity name. Output: ONE complete, production-ready dynamic pose sheet prompt for a diffusion model. The reference image is the sole identity and design source.

## OUTPUT CONTRACT
- Exactly six numbered sections ("1." … "6."), each ONE paragraph, no line breaks inside sections.
- No preamble, no markdown fences, no JSON, no notes.
- Descriptive prose: English.
- Every string rendered as visible text inside the sheet: English only (user-given proper nouns excepted), in double quotes, exact spelling and capitalization, monolingual. Rendered text is kept to the strict minimum listed in the sections: the title, one caption and ten short labels. Never add other text.
- Label placement is part of every label: wherever a label is defined or mentioned, state that it sits centered horizontally under its figure, below the floor line at the bottom of its cell, never in a corner of the cell and never above the figure. Repeat this placement in Sections 1, 3, 4 and 5.
- No pixel resolutions; sheet ratio expressed only as "4:3 landscape composition".
- Density: 50–170 words per section, 650–1200 words total.

## INTERNAL STEPS (do not output)
STEP 0 — VISUAL AUDIT: classify the entity type as one of: animal, stylized character, human, robot, vehicle, object, creature (always plain words with spaces, never a code word with underscores); identify the rendering medium; list only verifiable facts: face/head, hair or surface, accessories (with side), wardrobe or body covering from neck to feet, held items, signature optical effects (exact color order + location), footwear or feet, asymmetries. Never invent.
STEP 1 — IDENTITY LOCKS: condense the audit into 5–7 precise bullets (color + shape + position). They must reappear in Sections 3 and 6.
STEP 2 — DESIGN SYSTEM:
- CLOSED PALETTE: ink black; warm dark gray secondary text; warm off-white paper; light warm gray hairlines and floor lines; plus ONE accent color taken from the subject (its most distinctive color), used only for the title underline. No other hue.
- TYPOGRAPHY: high-contrast Didone display serif → title only; regular small ink-black sans-serif, uppercase, letter-spaced → caption and labels.
STEP 3 — ZONE MAP (always these coordinates):
Frame: thin ink-black border inset 3% from every edge.
Zone H HEADER: y 3–14%, full width.
Zone G GRID: x 3–97%, y 16–97%, ten equal cells in five columns and two rows, separated by thin light warm gray hairlines. Each cell holds one full-body figure standing on its own floor line with a soft gray contact shadow, and its short label centered under it.

## SECTION-BY-SECTION SPEC
1. OVERALL CANVAS & GLOBAL RENDERING STYLE: State 4:3 landscape; warm off-white paper; thin ink-black frame; Zone H and Zone G with their coordinates; the ten equal cells in five columns and two rows with hairline dividers; global rendering clause matched to the reference medium (anime: crisp variable-weight line art, soft cel shading; photoreal human: high-end live-action photography, accurate anatomy, no illustrated qualities; animal: naturalistic wildlife concept art; robot: hard-surface concept art with functional joints; vehicle or object: premium photoreal product rendering; creature: fantastical creature concept art); one even, soft key light from the upper left for all ten cells; plain paper background inside every cell, no scenery; each cell's label centered horizontally under its figure, below the floor line at the bottom of the cell; palette and typography cohesion sentence.
2. HEADER: Title = the user-given name in quotes, Didone serif, left-aligned in Zone H, with a thin accent-color underline; beneath it the caption in quotes "POSE SHEET" in letter-spaced uppercase sans-serif; nothing else in Zone H.
3. THE FIGURES: Ten full-body figures, every extremity visible and inside its cell, all at the same scale (the standing height of the character is the same in every cell, whatever the pose), each on its floor line with a soft oval contact shadow, with a clear strip below the floor line for the label; poses are dynamic: weight shifted onto one leg, torso twist, a clear line of action, hair and cloth showing the movement through their flow only — no motion blur, no speed lines, no dust, no effects drawn around the figure. FULL restatement of every identity lock (hair or surface and its length, eye color AND identical eye shape, skin or material, accessories with their exact sides, held item, signature effect with exact color order and location, wardrobe with fabric behavior, footwear). The same costume and the same face in all ten cells; handedness and asymmetries stay consistent in every pose.
4. THE TEN POSES, in reading order, each with its short label in quotes, centered horizontally under the figure, below the floor line at the bottom of the cell (say this placement for every label or once for the whole row, but never omit it). Row 1: "RUN" (mid-stride sprint, torso leaning forward, arms pumping, hair and loose cloth streaming back); "LEAP" (mid-air jump, knees tucked, one arm stretched forward, cloth lifting); "GUARD" (ready stance, knees bent, weight on the back leg, hands raised — holding the item seen in the reference on its exact side if there is one); "LUNGE" (deep forward lunge, front arm extended in a strike or thrust, back leg straight); "CROUCH" (low crouch, one hand touching the floor, head up, alert gaze). Row 2: "WALK" (relaxed forward stride caught mid-step, arms swinging); "LOOK BACK" (walking away, torso and head turned over the shoulder toward the viewer); "SIT" (sitting cross-legged on the floor line, back straight, hands on the knees); "KNEEL" (one knee down, the other foot flat, one hand on the raised knee); "REACH" (on tiptoe, one arm stretched high and forward, the other swinging back). For animals and creatures use the poses "GALLOP", "LEAP", "STALK" (low, head forward), "POUNCE", "CROUCH", "TROT", "LOOK BACK", "SIT", "REST" (lying down), "REAR UP"; for robots use the human poses with mechanically plausible joints; for vehicles and objects replace the poses with ten views or configurations on the floor line ("FRONT 3/4", "REAR 3/4", "SIDE", "FRONT", "REAR", "LOW ANGLE", "HIGH ANGLE", "TILTED", "OPEN", "CLOSED") and keep the cell structure.
5. TYPOGRAPHY HIERARCHY & PALETTE DISCIPLINE: Didone reserved for the title only; caption and labels in regular small ink-black uppercase letter-spaced sans-serif; the caption sits under the title and each label sits centered horizontally under its figure at the bottom of its cell, never in a corner; the single accent color used only for the title underline; warm off-white paper, light warm gray hairlines and floor lines, closed palette restated; rendering medium consistent in all ten cells.
6. IDENTITY PRESERVATION CONSTRAINTS: Open with "Preserve the exact visible design of <Name> from the reference image in all ten poses:" then one "same …" clause per lock (hair or surface including fringe and side locks; eye color AND identical eye shape; each accessory with its exact side; the held item; the signature effect in its exact location; wardrobe with identical fabric behavior; footwear). Commands: do not redesign, beautify, age-shift, simplify, add accessories; keep the reference medium throughout. Close with a negative block: no extra character or object, no identity, species, wardrobe or material drift, no changed proportions between cells, no missing extremities, no duplicated limbs, no figure cut by its cell edge, no merged or overlapping figures, no background scenery, no motion effects, no logo, watermark or decoration; every rendered text string must appear exactly as quoted above in English with exact spelling and capitalization.

## GOVERNING RULES
- Anchor on the image: every spatial, tonal and material claim comes from what is visibly there.
- Identity invariants survive every pose: face identity, accessory side and count, markings, rendering medium.
- Scale and anatomy discipline: ten figures at identical scale; all extremities visible; handedness consistent.
- Only what was asked: sheet construction only; never "clean up" or improve the subject.
- Labels: short English words, uppercase, legible; no other text anywhere.

## FINAL SELF-CHECK (internal, then output)
(1) Exactly six numbered single-paragraph sections? (2) Ten cells, five columns by two rows, in Section 1? (3) Every identity lock in Sections 3 and 6? (4) Accessory and held-item side identical in every mention? (5) All ten labels defined once, reused verbatim? (6) Entity type written in plain words, no underscores? (7) Nothing invented? (8) Every label said to be centered under its figure at the bottom of its cell, in Sections 1, 3, 4 and 5? If any check fails, rewrite internally, then emit ONLY the six sections.
"""#

  private static let staticPoses = #"""
CANVAS & STYLE: 4:3 landscape, off-white paper, thin black border. Extract and strictly preserve the exact visual style, rendering technique, line quality, shading method, and color palette from the reference image. The sheet must match the reference's aesthetic completely.

HEADER (y:3–14%): Character name "{{name}}" in Didone serif, left-aligned, with a thin underline in the main accent color taken from the reference. Caption below in letter-spaced uppercase sans-serif: "POSE SHEET".

GRID (x:3–97%, y:16–97%): 5 columns x 2 rows of equal cells, separated by thin light gray hairlines. Each cell: one full-body figure of the character on its own thin floor line with a soft gray contact shadow, plain paper background, no scenery. All ten figures at the same scale, every extremity visible and inside its cell. Poses are dynamic: weight shifted onto one leg, torso twist, a clear line of action; hair and cloth show the movement, with no motion blur and no speed lines. Strictly preserve the exact character design, face, clothing, accessories (same side), held items, materials, and visual effects from the reference in every pose. One short uppercase label per cell, centered horizontally under the figure, below the floor line at the bottom of the cell (never in a corner, never above the figure).
Row 1: "RUN" mid-stride sprint, torso leaning forward, hair and cloth streaming back. "LEAP" mid-air jump, knees tucked, one arm stretched forward. "GUARD" ready stance, knees bent, hands raised, holding the item from the reference if there is one. "LUNGE" deep forward lunge, front arm extended in a strike. "CROUCH" low crouch, one hand on the floor, alert gaze.
Row 2: "WALK" relaxed forward stride caught mid-step. "LOOK BACK" walking away, torso and head turned over the shoulder toward the viewer. "SIT" sitting cross-legged, back straight. "KNEEL" one knee down, one hand on the raised knee. "REACH" on tiptoe, one arm stretched high and forward.

TYPOGRAPHY & PALETTE: Title in Didone serif. Caption and labels in regular small sans-serif, uppercase, letter-spaced. Single accent color from the reference for the title underline only. Strict palette discipline matching the reference.
CONSTRAINTS: Strictly preserve the reference image's exact visual style, rendering technique, color palette, character design, proportions, and details in all ten cells. Extract all visual data from the input image. No style drift, no redesigns, no extra objects, no missing limbs, no duplicated limbs, no figure cut by its cell, no overlapping figures. All text must be exact English spelling as specified, and nothing else may be written.
"""#
}
