#!/usr/bin/env python3
"""Write CSBuiltIn.swift: the six prompt texts that ship inside the Character Sheet plug-in bundle.

A plug-in bundle holds only its library, so the texts become Swift strings. Run it from a folder that holds the six files
(by default the plug-in's data folder) whenever the texts change:

    python3 Scripts/make-builtin-texts.py [--source FOLDER] [--out Sources/CharacterSheet/CSBuiltIn.swift]
"""
import argparse
import os
import sys

FILES = [
    ("master", "master-prompt.txt"),
    ("staticPrompt", "static-prompt.txt"),
    ("masterExpressions", "master-prompt-expressions.txt"),
    ("staticExpressions", "static-prompt-expressions.txt"),
    ("masterPoses", "master-prompt-poses.txt"),
    ("staticPoses", "static-prompt-poses.txt"),
]
DEFAULT_SOURCE = os.path.expanduser("~/Library/Application Support/DT Hub/Data/CharacterSheet")
DEFAULT_OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "Sources", "CharacterSheet", "CSBuiltIn.swift")

HEADER = """// Generated by Scripts/make-builtin-texts.py; edit the six text files and run it again.
//
// The base sheet's master prompt and static prompt are taken from NeuroContent's ComfyUI workflow "Qwen Image 2.1 Character
// Design Sheet Maker" (https://civitai.com/models/2960750/qwen-image-21-character-design-sheet-maker-workflow); the
// expressions and poses prompts are derived from them. Used when the data folder has no file of the same name.
import Foundation

enum CSBuiltIn {
  static func text(for file: CSTemplateFile) -> String {
    switch file {
"""


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--source", default=DEFAULT_SOURCE)
    parser.add_argument("--out", default=DEFAULT_OUT)
    args = parser.parse_args()
    texts = {}
    for name, filename in FILES:
        path = os.path.join(args.source, filename)
        try:
            with open(path, encoding="utf-8") as handle:
                text = handle.read().strip()
        except OSError as error:
            sys.exit(f"error: cannot read {path}: {error}")
        if not text:
            sys.exit(f"error: {path} is empty")
        if '"""#' in text:
            sys.exit(f"error: {path} contains the raw-string terminator")
        texts[name] = text
    out = [HEADER]
    for name, _ in FILES:
        out.append(f"    case .{name}: return {name}\n")
    out.append("    }\n  }\n")
    for name, _ in FILES:
        out.append(f'\n  private static let {name} = #"""\n{texts[name]}\n"""#\n')
    out.append("}\n")
    with open(args.out, "w", encoding="utf-8") as handle:
        handle.write("".join(out))
    print(f"{os.path.normpath(args.out)}  ({sum(len(t) for t in texts.values())} characters)")


if __name__ == "__main__":
    main()
